type Country = {
    country: string,
    code: string,
}

export const countries: Country[] = [
    { country: 'Albania', code: '+355' },
    { country: 'Andorra', code: '+376' },
    { country: 'Austria', code: '+43' },
    { country: 'Belarus', code: '+375' },
    { country: 'Belgium', code: '+32' },
    { country: 'Bosnia and Herzegovina', code: '+387' },
    { country: 'Bulgaria', code: '+359' },
    { country: 'Croatia', code: '+385' },
    { country: 'Cyprus', code: '+357' },
    { country: 'Czech Republic', code: '+420' },
    { country: 'Denmark', code: '+45' },
    { country: 'Estonia', code: '+372' },
    { country: 'Finland', code: '+358' },
    { country: 'France', code: '+33' },
    { country: 'Germany', code: '+49' },
    { country: 'Greece', code: '+30' },
    { country: 'Hungary', code: '+36' },
    { country: 'Iceland', code: '+354' },
    { country: 'Ireland', code: '+353' },
    { country: 'Italy', code: '+39' },
    { country: 'Kosovo', code: '+383' },
    { country: 'Latvia', code: '+371' },
    { country: 'Liechtenstein', code: '+423' },
    { country: 'Lithuania', code: '+370' },
    { country: 'Luxembourg', code: '+352' },
    { country: 'Malta', code: '+356' },
    { country: 'Moldova', code: '+373' },
    { country: 'Monaco', code: '+377' },
    { country: 'Montenegro', code: '+382' },
    { country: 'Netherlands', code: '+31' },
    { country: 'North Macedonia', code: '+389' },
    { country: 'Norway', code: '+47' },
    { country: 'Poland', code: '+48' },
    { country: 'Portugal', code: '+351' },
    { country: 'Romania', code: '+40' },
    { country: 'San Marino', code: '+378' },
    { country: 'Serbia', code: '+381' },
    { country: 'Slovakia', code: '+421' },
    { country: 'Slovenia', code: '+386' },
    { country: 'Spain', code: '+34' },
    { country: 'Sweden', code: '+46' },
    { country: 'Switzerland', code: '+41' },
    { country: 'Ukraine', code: '+380' },
    { country: 'United Kingdom', code: '+44' },
    { country: 'Vatican City', code: '+39' },
];
